[package]
name = "poseidon"
version = "0.0.1"
edition = "2018"
license = "GPL-3.0"

[dependencies]
ff = {package="ff_ce" , version="0.13", features = ["derive"]}
rand = "0.4"
serde_json = "1.0"

[dev-dependencies]
criterion = "0.3"
